name: Test Suite

defaults:
  run:
    working-directory: backend

on:
  push:
    branches: [main]

jobs:
  tests:
    name: Smart Contract Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js v22.1.0
        uses: actions/setup-node@v1
        with:
          node-version: v22.1.0

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npx hardhat test